name: Tests
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "Dockerfile"
      - "scripts/**"
permissions:
  contents: read
jobs:
  test:
    name: Image Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Run tests
        run: make test
